spring:
  application:
    name: westwood
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: qa@mail.com
    password: qa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
